name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/goreleaser
    steps:
    - uses: actions/checkout@v2
    - id: version
      run: |
        IMAGE_VERSION=v$(grep "^ENV GORELEASER_VERSION=" Dockerfile|awk -F= '{print $2}')
        echo "IMAGE_VERSION=${IMAGE_VERSION}" >> $GITHUB_ENV
        echo "IMAGE_VERSION_SUB=${IMAGE_VERSION%.*}" >> $GITHUB_ENV
    - name: Login to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION_SUB }}
          ${{ env.IMAGE_NAME }}:latest
    - name: Build and push bullseye
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile-bullseye
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}-bullseye
          ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION_SUB }}-bullseye
          ${{ env.IMAGE_NAME }}:bullseye
    - name: Build and push buster
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile-buster
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}-buster
          ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION_SUB }}-buster
          ${{ env.IMAGE_NAME }}:buster